version: '3.8'
# 命令执行 docker-compose -f docker-compose-app.yml up -d
services:
  big-market-app:
    image: peregrinecalder/big-market-app:2.0
    container_name: big-market-app
    restart: always
    ports:
      - "8091:8091"
    environment:
      - TZ=PRC
      - SERVER_PORT=8091
      - APP_CONFIG_API_VERSION=v1
      - APP_CONFIG_CROSS_ORIGIN=*
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=ahhfzhp20011119
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_HIKARI_POOL_NAME=Retail_HikariCP
      - SPRING_REDIS_HOST=117.72.67.92
      - SPRING_REDIS_PORT=16379
      - SPRING_RABBITMQ_ADDRESSES=117.72.67.92
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin
      - THREAD_POOL_EXECUTOR_CORE_POOL_SIZE=20
      - THREAD_POOL_EXECUTOR_MAX_POOL_SIZE=50
      - THREAD_POOL_EXECUTOR_KEEP_ALIVE_TIME=5000
      - THREAD_POOL_EXECUTOR_BLOCK_QUEUE_SIZE=5000
      - THREAD_POOL_EXECUTOR_POLICY=CallerRunsPolicy
      - MYBATIS_MAPPER_LOCATIONS=classpath:/mybatis/mapper/*.xml
      - MYBATIS_CONFIG_LOCATION=classpath:/mybatis/config/mybatis-config.xml
      - MINI_DB_ROUTER_JDBC_DATASOURCE_DBCOUNT=2
      - MINI_DB_ROUTER_JDBC_DATASOURCE_TBCOUNT=4
      - MINI_DB_ROUTER_JDBC_DATASOURCE_DEFAULT=db00
      - MINI_DB_ROUTER_JDBC_DATASOURCE_ROUTERKEY=userId
      - MINI_DB_ROUTER_JDBC_DATASOURCE_LIST=db01,db02
      - MINI_DB_ROUTER_JDBC_DATASOURCE_DB00_URL=jdbc:mysql://117.72.67.92:13306/big_market?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
      - MINI_DB_ROUTER_JDBC_DATASOURCE_DB00_USERNAME=root
      - MINI_DB_ROUTER_JDBC_DATASOURCE_DB00_PASSWORD=ahhfzhp20011119
      - MINI_DB_ROUTER_JDBC_DATASOURCE_DB01_URL=jdbc:mysql://117.72.67.92:13306/big_market_01?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
      - MINI_DB_ROUTER_JDBC_DATASOURCE_DB01_USERNAME=root
      - MINI_DB_ROUTER_JDBC_DATASOURCE_DB01_PASSWORD=ahhfzhp20011119
      - MINI_DB_ROUTER_JDBC_DATASOURCE_DB02_URL=jdbc:mysql://117.72.67.92:13306/big_market_02?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
      - MINI_DB_ROUTER_JDBC_DATASOURCE_DB02_USERNAME=root
      - MINI_DB_ROUTER_JDBC_DATASOURCE_DB02_PASSWORD=ahhfzhp20011119
    volumes:
      - ./log:/data/log
    networks:
      - my-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  big-market-front-app:
    container_name: big-market-front-app
    image: peregrinecalder/big-market-front-app:2.0
    restart: always
    networks:
      - my-network
    ports:
      - 3000:3000
    environment:
      - API_HOST_URL=http://117.72.67.92:8091
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://0.0.0.0:3000/" ]
      interval: 1m
      timeout: 10s
      retries: 3

networks:
  my-network:
    driver: bridge